### ISSUE TITLE
Reproducing the conditional generation

### ISSUE THREAD

**Issue by TaehoonK** [Yasoz/DiffTraj#15]
Dear @Yasoz , 

I have several questions about using the DiffTraj model. 

1. I want to get confirmation on how to reproduce the conditional generation (Annex.C.4 in the paper). 
I trained a model with another trajectory dataset with preprocessed conditional properties (the same as the public one: **departure_time, total_distance, total_travel_time, total_length_of_points, avg_distance_between_points, avg_speed, start_area_id, end_area_id**).
Unfortunately, when I generated synthetic trajectories with conditional properties, 'start_area_id' and 'end_area_id' did not work well (this means these properties did not affect the generated results): Even if I used the same 'start_area_id' and 'end_area_id', the generated results covered the whole domain (the entire area of the dataset). However, the public DiffTraj model ("model.pt" in this repository) worked well.
I think it depends on the hyperparameters in the "config.py." Please tell me the hyperparameters used for public DiffTraj model training. Would you happen to have any comments for me about why this result occurred? I used almost the same parameters as the current config, except 'traj_length = 150'. Also, I set up a different size grid domain (21 by 13 = 273) and, of course, modified the 'sid_embedding' and 'eid_embedding' sizes within the WideAndDeep network to 274. 

2. If I want to reproduce the results in Annex C.4 in the paper, like Figures 7 and 8, do I need to train each model with a different 'guidance_scale'? When I tried the different 'guidance_scale' in the config to generate synthetic trajectory with the public DiffTraj model, I couldn't get the expected results like Figures 7 and 8. 

3. In this repository and your paper, you are using a trajectory with latitude and longitude location. However, when I check the "Traj_Generation.ipynb", the coordinate values are rescaling with the 'mean' and 'std' of trajectory coordinates. This means that when you trained the model, you used the standardized coordinate values instead of the latitude and longitude values. I understand the numerical values in the conditional information should be standardized, but do the coordinates also need to be standardized? Does it affect the performance of the model? 

4. The “Model” in the “Traj_UNet.py” contains a conditional attention block according to the ‘attn_resolutions’ ([code ref](https://github.com/Yasoz/DiffTraj/blob/main/utils/Traj_UNet.py#L292)). However, the current resolution value in the config (i.e., traj_len = 200) is not matched with ‘attn_resolution = [16]’ when the resolution is changed according to the downsampling (and upsampling) process. Is this by design?

5. I want to evaluate my results with the same metrics as your paper. Could you share the evaluation codes? 

Best regards, 
Taehoon

**Comment by Yasoz** [comment]
Dear Taehoon,

Thanks for your interest in our work. Here are some clarifications to some of your questions:

1. I am using hyperparameters that are consistent with the settings in the code (config.py), otherwise it will not be possible to reproduce the results using **model.pt**. Also all the recommended parameters given in Table 3 can be used to train the model. I think the number of grids does not affect the results, you need to make sure that the start and end points are actually in the grid, as well as the order.
2. You need to retrain the model for a different guidance_scale, please note that due to the random behavior of the generated trajectories, you may not achieve perfect results on your dataset. You can try increasing this parameter's magnitude.
3. Standardization can make a great difference to the results of an experiment, so please standardize your data (latitude and longitude) before training your model! Please do not standardize the gird number :)
4. I'm using the original repository settings here, in which the trajectory does not match attn_resolution, as you can see from the model structure.
5. Please compute the heat map matrices for the original and generated trajectories first and then use the following code.
```python
def JS_divergence(matrix1, matrix2):
    matrix1 = matrix1 + 1e-6
    matrix2 = matrix2 + 1e-6
    matrix1 = matrix1 / matrix1.sum()
    matrix2 = matrix2 / matrix2.sum()
    m = (matrix1 + matrix2) / 2
    return 0.5 * np.sum(matrix1 * np.log(matrix1 / m)) + 0.5 * np.sum(
        matrix2 * np.log(matrix2 / m))
```

Best,
Yuanshao

**Comment by TaehoonK** [comment]
Dear Yuanshao,

Thanks for your kind answer! 
I trained the model with the default config.py and standardized coordinates. 
And get better results: the spatial density of the generated trajectories is more similar to the original one. 
Unfortunately, the **start_grid_id** and **end_grid_id** still does not work. 
Anyway, I will train the model with different hyperparameters. 
Lastly, thank you for sharing the JS_divergence function. 

Best regards,
Taehoon

**Comment by jongsh** [comment]
@TaehoonK 

Dear Taehoon,

I am encountering a similar query as the one raised in the mentioned issue. Could you please clarify how the standardized coordinates are determined? Specifically, I am interested in whether these coordinates are computed based on the entire dataset of trajectories or if they are derived from the central coordinates within the city area.

Best regards,
Jongsh
